{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "       ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n       urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000207AEB88D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=63568): Max retries exceeded with url: /session/13d2fdf06030afe651a33ea3494fadb3/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000207AEB88D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000207AEBB4D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=63568): Max retries exceeded with url: /session/13d2fdf06030afe651a33ea3494fadb3/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000207AEBB4D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_tc_reg_06[test_case0]", "rerun": "0"}}, "suite_name": "tests/test_TC_Reg_06.py"}}}, "date": "September 02, 2025", "start_time": 1756817967.337745, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}